version: 2

# ---------------------------------------------------------------------------
# ANCHORS (bits of YAML that can be reused)
# ---------------------------------------------------------------------------

docker_image: &docker_image
  docker:
    - image: circleci/openjdk:8-jdk

setup_pgp: &setup_pgp
  run:
    name: Set-up PGP credentials
    command: mkdir -p ~/.sbt/gpg && (echo $PGP_KEY | base64 --decode --ignore-garbage > ~/.sbt/gpg/secring.asc) && (echo $PGP_CREDS | base64 --decode --ignore-garbage > ~/.sbt/pgp.credentials)

dependency_cache_key: &dependency_cache_key v2-dependencies--{{ checksum "build.sbt" }}

restore_dependency_cache: &restore_dependency_cache
  restore_cache:
    name: Restoring dependency cache
    keys:
    - *dependency_cache_key
    # fallback to using the latest cache if no exact match is found
    - v2-dependencies--

save_dependency_cache: &save_dependency_cache
  save_cache:
    paths:
      - ~/.m2
      - ~/.ivy2
      - ~/.sbt
    key: v2-dependencies--{{ checksum "build.sbt" }}

load_workspace: &load_workspace
  attach_workspace:
    at: .

persist_workspace: &persist_workspace
  persist_to_workspace:
    root: .
    paths:
      - ./*

# ---------------------------------------------------------------------------
# JOB DEFINITIONS
# ---------------------------------------------------------------------------

jobs:
  checkout:
    <<: *docker_image
    steps:
      - checkout
      - *persist_workspace

  build:
    <<: *docker_image
    steps:
      - *load_workspace
      - *restore_dependency_cache
      - run:
          name: Compile
          command: sbt ";compile; test:compile"
      - *save_dependency_cache
      - *persist_workspace

  test:
    <<: *docker_image
    steps:
      - *load_workspace
      - *restore_dependency_cache
      - run:
          name: Run tests and push coverage to codacy + coveralls
          command: sbt coverage test && sbt coverageReport && sbt coverageAggregate && sbt codacyCoverage && sbt coveralls

  release:
    <<: *docker_image
    steps:
      - *load_workspace
      - *restore_dependency_cache
      - *setup_pgp
      - run:
          name: Run sbt release task
          command: sbt "release with-defaults"

# ---------------------------------------------------------------------------
# WORKFLOWS
# ---------------------------------------------------------------------------

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: master
      - build:
          requires:
            - checkout
      - test:
          requires:
            - build
  release:
    jobs:
      - checkout:
          filters:
            branches:
              only: master
      - release:
          requires:
            - checkout