version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout
      - run: mkdir -p ~/.sbt/gpg
      - run: echo $PGP_KEY | base64 --decode --ignore-garbage > ~/.sbt/gpg/secring.asc
      - run: echo $PGP_CREDS | base64 --decode --ignore-garbage > ~/.sbt/pgp.credentials

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
        
      # run tests!
      - run: sbt coverage test && sbt coverageReport && sbt coverageAggregate && sbt codacyCoverage && sbt coveralls
