version: 2

# ---------------------------------------------------------------------------
# ANCHORS (bits of YAML that can be reused)
# ---------------------------------------------------------------------------

docker_image: &docker_image
  docker:
    - image: circleci/openjdk:8-jdk

setup_pgp: &setup_pgp
  run:
    name: Set-up PGP credentials
    command: mkdir -p ~/.sbt/gpg && (echo $PGP_KEY | base64 --decode --ignore-garbage > ~/.sbt/gpg/secring.asc) && (echo $PGP_CREDS | base64 --decode --ignore-garbage > ~/.sbt/pgp.credentials)

dependency_cache_key: &dependency_cache_key v2-dependencies--{{ checksum "build.sbt" }}

restore_dependency_cache: &restore_dependency_cache
  restore_cache:
    name: Restoring dependency cache
    keys:
    - *dependency_cache_key
    # fallback to using the latest cache if no exact match is found
    - v2-dependencies--

save_dependency_cache: &save_dependency_cache
  save_cache:
    paths:
      - ~/.m2
      - ~/.ivy2
      - ~/.sbt
    key: *dependency_cache_key

persist_workspace: &persist_workspace
  persist_to_workspace:
    root: .
    paths:
      - ./*

load_workspace: &load_workspace
  attach_workspace:
    at: .

tut_and_commit: &tut_and_commit
  run:
    name: Run tut and then commit any changes
    command: (sbt tut && git diff --exit-code --name-only README.md) || echo "readme changed"

# ---------------------------------------------------------------------------
# JOB DEFINITIONS
# ---------------------------------------------------------------------------

jobs:

  test:
    <<: *docker_image
    steps:
      - checkout
      - *restore_dependency_cache
      - run:
          name: Run tests and push coverage to codacy + coveralls
          command: sbt coverage test && sbt coverageReport && sbt coverageAggregate && sbt codacyCoverage && sbt coveralls
      - *save_dependency_cache
      - *persist_workspace

  release:
    <<: *docker_image
    steps:
      - *load_workspace
      - checkout
      - *restore_dependency_cache
      - *setup_pgp
      - run:
          name: Set up github user
          command: git config --global user.name "wunderk1nd-e" && git config --global user.email "elias@k1nd.ltd"
      - run:
          name: Run sbt release task
          command: sbt "release with-defaults"

# ---------------------------------------------------------------------------
# WORKFLOWS
# ---------------------------------------------------------------------------

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
